### ISSUE TITLE
Strange memory allocation in EagleXML

### ISSUE THREAD

**Issue by alex85k** [alacarte-maps/alacarte#56]
Noticed this problem when running tests on Windows. 
Debug runtime gives me multiple assertions when deallocating memory. 

Consider Stack class
https://github.com/alacarte-maps/alacarte/blob/master/extras/eaglexml/eaglexml.hpp#L2793
```C++
template<typename T, std::size_t Size = EAGLEXML_STD_STACKSEGMENT_SIZE>
		class Stack
```
Note that EAGLEXML_STD_STACKSEGMENT_SIZE = 1024 .
Inside the class we have only one allocation:
https://github.com/alacarte-maps/alacarte/blob/master/extras/eaglexml/eaglexml.hpp#L2995
```C++
StackSegment* allocSegment()
			{
				StackSegment* segment = allocator.allocate(1);
				segment->init();
				return segment;
			}
```
But the destructor gives Size value to .deallocate() (not 1). This is causing the assertion:
```C++
~StringStack()
{
	StackSegment* segment = m_bottom;
	while(segment)
	{
		StackSegment* toDelete = segment;
		segment = segment->next;
		allocator.destroy(toDelete);
		allocator.deallocate(toDelete, Size);
	}
}
```
http://en.cppreference.com/w/cpp/memory/allocator/deallocate

However, valgring does not detect a problem. Maybe there is addtional check in stdd::allocator.dealocate on Linux that ignores 1024 but analogous part breaks with assertion on MSVC runtime.

Not sure if my "solution" is correct: https://github.com/alex85k/alacarte/commit/4854cc7b63d2671233f701073c96aaa1283c1c24

I understand that this should go upstream to EagleXML but it is not quite alive...
https://code.google.com/p/eaglexml/

**Comment by alex85k** [comment]
The best solution may be to replace https://github.com/alacarte-maps/alacarte/blob/master/src/importer/importer.cpp
and EagleXML with libosmium getting .pbf / .bz2 / .gz  support for free (we already have boost dependency).

**Comment by SrTobi** [comment]
:) eaglexml is a project of mine. It was migrated to github https://github.com/SrTobi/eaglexml some time ago.

I fixed the problem there. Maybe we can add it as an submodule... or we can migrate to libosmium

**Comment by alex85k** [comment]
> :) eaglexml is a project of mine. It was migrated to github https://github.com/SrTobi/eaglexml some time ago.
> I fixed the problem there. Maybe we can add it as an submodule... or we can migrate to libosmium
Then we should keep it because we know whom to ask for fixes. :)

**Comment by SrTobi** [comment]
year... it is super fast anyway :) should i correct the error directly or do you want

**Comment by alex85k** [comment]
Thank you :)
