### ISSUE TITLE
AUR packaging

### ISSUE THREAD

**Issue by florianjacob** [alacarte-maps/alacarte#73]
Prepare an AUR package to be ready for 0.4.0.

It should live in its own alacarte-maps repository so one can make pull requests etc, as AUR sadly lacks a mechanism to send in improvements easily.

Many bonus points to include a zip command in either `CMakeLists.txt` or the PKGBUILD, so we don't have to have the compressed manpages in the repository. Maybe https://cmake.org/pipermail/cmake/2010-September/039781.html can be of help.

Advantages of non-compressed manpages: The manpage is readable from github and could be linked to from the website, and it would be possible to show diffs betwen versions.

**Comment by Semoar** [comment]
PKGBUILD for AUR can be found in https://github.com/alacarte-maps/PKGBUILD, just needs the checksum of 0.4.0.
Manpages generation has been added in a097dcf2bc60fdce6597ce38695be7e21db8ffbc
