### ISSUE TITLE
Add different styles to the live demo

### ISSUE THREAD

**Issue by Scheirle** [alacarte-maps/alacarte#82]
In the live demo it should be possible to select different map styles.

**Comment by florianjacob** [comment]
Indeed! We actually had that feature at some point in the past, right? Probably forgot some leaflet options on migrating?

**Comment by Semoar** [comment]
Yup, I just forgot about that while migrating, the server still offers two styles by default. I added a selector for different styles to the live demo in alacarte-maps/alacarte-maps.github.io@79a14b4537652e15b63644a7de8c59f372f2571c
